apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-edgeconnect
  namespace: default
roleRef:
  kind: Role
  name: role-edgeconnect
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: edgeconnect-deployment-rollout-restarter
  namespace: dynatrace