apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-edgeconnect
  namespace: default
rules:
  - apiGroups: [""] 
    resources: ["pods"] 
    verbs: ["get", "list", "delete"] 
  - apiGroups: [""] 
    resources: ["pods/log"] 
    verbs: ["get", "list"] 
  - apiGroups: [""] 
    resources: ["configmaps"] 
    verbs: ["patch", "get", "delete"] 
  - apiGroups: ["batch"] 
    resources: ["jobs"] 
    verbs: ["get", "list", "create", "patch", "delete"] 
  - apiGroups: [""] 
    resources: ["persistentvolumeclaims"] 
    verbs: ["get", "patch", "delete"] 
  - apiGroups: ["apps"] 
    resources: ["deployments"] 
    verbs: ["patch", "get", "create", "delete"] 