apiVersion: v1
kind: Secret
metadata:
  name: aut-edgeconnect-oauth
  namespace: dynatrace
stringData:
  oauth-client-id: dt0s02.XXXXXXX
  oauth-client-secret: dt0s02.XXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX